name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Correctly using latest version

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Updated to latest stable
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Lint code
        run: docker compose run --rm app sh -c "flake8"
